// Auto-generated by scripts/set-api-base.js
export const API_BASE = 'https://script.google.com/a/macros/kbcgroup.ac.jp/s/AKfycbwMkF8A6TtuEpFAyfP80sO51Pz5W4h8SRd6PD97VMU30hTZyo6SnM1jjermjL1J-0PR/exec'
export const COURT_PASSWORD = '2026'
export const SHEET_ID = '1n9s8l7mXo2a3b4c5d6e7f8g9h0i1j2k3l4m5n6o7p8q9r0s1t2u3v4w5x6y7z8'

